In [1]:
import torch

# Tensor A de dimensiones (3, 1)
A = torch.tensor([[1], [2], [3]])

# Tensor B de dimensiones (1, 4)
B = torch.tensor([[10, 20, 30, 40]])

# Suma con broadcasting
C = A + B
print(f"Tensor A de dimensiones {A.shape}:\n{A}")
print(f"Tensor B de dimensiones {B.shape}:\n{B}")
print(f"Suma C de dimensiones {C.shape}:\n{C}")


Tensor A de dimensiones torch.Size([3, 1]):
tensor([[1],
        [2],
        [3]])
Tensor B de dimensiones torch.Size([1, 4]):
tensor([[10, 20, 30, 40]])
Suma C de dimensiones torch.Size([3, 4]):
tensor([[11, 21, 31, 41],
        [12, 22, 32, 42],
        [13, 23, 33, 43]])


In [2]:
# Crear un tensor de dimensiones (2, 3)
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Transponer el tensor
tensor_t = tensor.t()
print(f"Tensor original de dimensiones {tensor.shape}:\n{tensor}")
print(f"Tensor transpuesto de dimensiones {tensor_t.shape}:\n{tensor_t}")


Tensor original de dimensiones torch.Size([2, 3]):
tensor([[1, 2, 3],
        [4, 5, 6]])
Tensor transpuesto de dimensiones torch.Size([3, 2]):
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [3]:
# Tensor de dimensiones (2, 3, 4)
tensor = torch.rand(2, 3, 4)

# Permutar ejes
tensor_permutado = tensor.permute(2, 0, 1)
print(f"Tensor original de dimensiones {tensor.shape}")
print(f"Tensor permutado de dimensiones {tensor_permutado.shape}")


Tensor original de dimensiones torch.Size([2, 3, 4])
Tensor permutado de dimensiones torch.Size([4, 2, 3])


In [4]:
# Crear un tensor de dimensiones (2, 3)
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Cambiar la forma a (3, 2)
tensor_reshaped = tensor.reshape(3, 2)
print(f"Tensor original de dimensiones {tensor.shape}:\n{tensor}")
print(f"Tensor reshaped de dimensiones {tensor_reshaped.shape}:\n{tensor_reshaped}")


Tensor original de dimensiones torch.Size([2, 3]):
tensor([[1, 2, 3],
        [4, 5, 6]])
Tensor reshaped de dimensiones torch.Size([3, 2]):
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [5]:
tensor_reshaped_auto = tensor.reshape(-1, 2)
print(f"Tensor reshaped con -1 de dimensiones {tensor_reshaped_auto.shape}:\n{tensor_reshaped_auto}")


Tensor reshaped con -1 de dimensiones torch.Size([3, 2]):
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [6]:
# Definir un vector
vector = torch.tensor([3.0, -4.0, 5.0])

# Norma L1
norma_l1 = torch.norm(vector, p=1)
print(f"Norma L1 del vector {vector.numpy()}: {norma_l1.item()}")

# Norma L2
norma_l2 = torch.norm(vector, p=2)
print(f"Norma L2 del vector {vector.numpy()}: {norma_l2.item()}")

# Norma L-infinito
norma_linf = torch.norm(vector, p=float('inf'))
print(f"Norma L-infinito del vector {vector.numpy()}: {norma_linf.item()}")


Norma L1 del vector [ 3. -4.  5.]: 12.0
Norma L2 del vector [ 3. -4.  5.]: 7.071067810058594
Norma L-infinito del vector [ 3. -4.  5.]: 5.0


In [7]:
# Definir matrices
A = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
B = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

# Producto Hadamard
C = A * B  # Operación elemento a elemento
print(f"Matriz A:\n{A}")
print(f"Matriz B:\n{B}")
print(f"Producto Hadamard (A * B):\n{C}")


Matriz A:
tensor([[1., 2.],
        [3., 4.]])
Matriz B:
tensor([[5., 6.],
        [7., 8.]])
Producto Hadamard (A * B):
tensor([[ 5., 12.],
        [21., 32.]])


In [8]:
# Crear un tensor
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)

# Suma total
suma_total = torch.sum(tensor)
print(f"Suma total de los elementos del tensor: {suma_total.item()}")

# Suma por filas (dim=1)
suma_filas = torch.sum(tensor, dim=1)
print(f"Suma por filas: {suma_filas}")

# Suma por columnas (dim=0)
suma_columnas = torch.sum(tensor, dim=0)
print(f"Suma por columnas: {suma_columnas}")


Suma total de los elementos del tensor: 21.0
Suma por filas: tensor([ 6., 15.])
Suma por columnas: tensor([5., 7., 9.])


In [9]:
A = torch.rand(4, 1, 3)
B = torch.rand(1, 2, 1)
C = A + B
print(f"Dimensiones de A: {A.shape}")
print(f"Dimensiones de B: {B.shape}")
print(f"Dimensiones de C (A + B): {C.shape}")


Dimensiones de A: torch.Size([4, 1, 3])
Dimensiones de B: torch.Size([1, 2, 1])
Dimensiones de C (A + B): torch.Size([4, 2, 3])


In [10]:
tensor = torch.rand(2, 3, 4, 5)
tensor_permutado = tensor.permute(3, 2, 1, 0)
print(f"Dimensiones del tensor original: {tensor.shape}")
print(f"Dimensiones del tensor permutado: {tensor_permutado.shape}")


Dimensiones del tensor original: torch.Size([2, 3, 4, 5])
Dimensiones del tensor permutado: torch.Size([5, 4, 3, 2])


In [11]:
u = torch.tensor([1.0, 2.0, 3.0])
v = torch.tensor([4.0, 5.0, 6.0])

# Distancia Euclidiana
distancia_euclidiana = torch.norm(u - v, p=2)
print(f"Distancia Euclidiana entre u y v: {distancia_euclidiana.item()}")

# Distancia de Manhattan
distancia_manhattan = torch.norm(u - v, p=1)
print(f"Distancia de Manhattan entre u y v: {distancia_manhattan.item()}")


Distancia Euclidiana entre u y v: 5.196152210235596
Distancia de Manhattan entre u y v: 9.0
