In [2]:
import torch

# Definir los vectores
a = torch.tensor([1, 3, -5], dtype=torch.float32)
b = torch.tensor([4, -2, -1], dtype=torch.float32)

# Calcular el producto punto
producto_punto = torch.dot(a, b)
print(f"Producto punto de {a.numpy()} y {b.numpy()}: {producto_punto.item()}")


Producto punto de [ 1.  3. -5.] y [ 4. -2. -1.]: 3.0


In [3]:
# Definir los vectores
a = torch.tensor([1, 2], dtype=torch.float32)
b = torch.tensor([3, 4, 5], dtype=torch.float32)

# Calcular el producto externo
producto_externo = torch.ger(a, b)
print(f"Producto externo de {a.numpy()} y {b.numpy()}:\n{producto_externo}")


Producto externo de [1. 2.] y [3. 4. 5.]:
tensor([[ 3.,  4.,  5.],
        [ 6.,  8., 10.]])


In [4]:
# Definir los vectores
a = torch.tensor([1, 0, 0], dtype=torch.float32)
b = torch.tensor([0, 1, 0], dtype=torch.float32)

# Calcular el producto cruz
producto_cruz = torch.cross(a, b)
print(f"Producto cruz de {a.numpy()} y {b.numpy()}: {producto_cruz.numpy()}")


Producto cruz de [1. 0. 0.] y [0. 1. 0.]: [0. 0. 1.]


<ipython-input-4-66fc56238b76>:6: UserWarning: Using torch.cross without specifying the dim arg is deprecated.
Please either pass the dim explicitly or simply use torch.linalg.cross.
The default value of dim will change to agree with that of linalg.cross in a future release. (Triggered internally at ../aten/src/ATen/native/Cross.cpp:62.)
  producto_cruz = torch.cross(a, b)


In [5]:
# Definir las matrices
A = torch.tensor([[1, 2],
                  [3, 4]], dtype=torch.float32)
B = torch.tensor([[5, 6],
                  [7, 8]], dtype=torch.float32)

# Multiplicación de matrices
C = torch.matmul(A, B)
print(f"Matriz A:\n{A}")
print(f"Matriz B:\n{B}")
print(f"Producto matricial A x B:\n{C}")


Matriz A:
tensor([[1., 2.],
        [3., 4.]])
Matriz B:
tensor([[5., 6.],
        [7., 8.]])
Producto matricial A x B:
tensor([[19., 22.],
        [43., 50.]])


In [6]:
# Multiplicación A x B
C = torch.matmul(A, B)

# Multiplicación B x A
D = torch.matmul(B, A)

print(f"A x B:\n{C}")
print(f"B x A:\n{D}")


A x B:
tensor([[19., 22.],
        [43., 50.]])
B x A:
tensor([[23., 34.],
        [31., 46.]])


In [7]:
# Producto elemento a elemento
E = A * B
print(f"Producto elemento a elemento A * B:\n{E}")


Producto elemento a elemento A * B:
tensor([[ 5., 12.],
        [21., 32.]])


In [8]:
# Crear tensores aleatorios
T = torch.rand(2, 3, 4)
S = torch.rand(4, 5, 6)

# Contracción sobre la tercera dimensión de T y la primera de S
R = torch.tensordot(T, S, dims=([2], [0]))
print(f"Dimensiones de T: {T.shape}")
print(f"Dimensiones de S: {S.shape}")
print(f"Dimensiones del resultado R: {R.shape}")


Dimensiones de T: torch.Size([2, 3, 4])
Dimensiones de S: torch.Size([4, 5, 6])
Dimensiones del resultado R: torch.Size([2, 3, 5, 6])


In [9]:
# Definir los tensores
A = torch.tensor([1, 2], dtype=torch.float32)
B = torch.tensor([3, 4, 5], dtype=torch.float32)

# Producto tensorial
C = torch.ger(A, B)
print(f"Producto tensorial de A y B:\n{C}")


Producto tensorial de A y B:
tensor([[ 3.,  4.,  5.],
        [ 6.,  8., 10.]])


In [10]:
# Definir las matrices
A = torch.tensor([[1, 2],
                  [3, 4]], dtype=torch.float32)
B = torch.tensor([[5, 6],
                  [7, 8]], dtype=torch.float32)

# Multiplicación de matrices usando einsum
C = torch.einsum('ij,jk->ik', A, B)
print(f"Resultado usando einsum:\n{C}")


Resultado usando einsum:
tensor([[19., 22.],
        [43., 50.]])


In [11]:
# Simular una capa densa
entrada = torch.rand(1, 784)  # Vector de entrada (ejemplo: imagen aplanada de 28x28 píxeles)
pesos = torch.rand(784, 128)  # Pesos de la capa
sesgos = torch.rand(128)      # Sesgos de la capa

# Calcular la salida
salida = torch.matmul(entrada, pesos) + sesgos
print(f"Dimensiones de la salida: {salida.shape}")


Dimensiones de la salida: torch.Size([1, 128])
